// Creating Contact Actions
export const FETCH_USERS_REQUEST  = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS  = 'FETCH_USERS_SUCCESS';
export const  FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const ADD_CONTACT = 'ADD_CONTACT';
export const EDIT_CONTACT  = 'EDIT_CONTACT';
export const DELETE_CONTACT  = 'DELETE_CONTACT';